// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async greet(name: string): Promise<string> {
    return await TAURI_INVOKE("greet", { name });
  },
  async executeCommand(
    command: string,
    args: string[],
  ): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("execute_command", { command, args }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getSystemInfo(): Promise<SystemInfo> {
    return await TAURI_INVOKE("get_system_info");
  },
  async createPluginWindow(
    windowId: string,
    config: JsonValue,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("create_plugin_window", { windowId, config }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async updatePluginWindow(
    windowId: string,
    config: JsonValue,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("update_plugin_window", { windowId, config }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async closePluginWindow(windowId: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("close_plugin_window", { windowId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async focusPluginWindow(windowId: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("focus_plugin_window", { windowId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async setWindowFullscreen(
    windowId: string,
    fullscreen: boolean,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("set_window_fullscreen", {
          windowId,
          fullscreen,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async requestScreenshotPermission(): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("request_screenshot_permission"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async toggleWindowVisibility(): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("toggle_window_visibility"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async hideWindow(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("hide_window") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getApplications(): Promise<Result<AppInfoWrapper[], string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_applications") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getFrontmostApp(): Promise<Result<AppInfoWrapper | null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_frontmost_app") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async refreshApplicationsList(): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("refresh_applications_list"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async refreshApplicationsListInBg(): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("refresh_applications_list_in_bg"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Hide All Apps Except Frontmost (macOS only)
   */
  async hideAllAppsExceptFrontmost(): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("hide_all_apps_except_frontmost"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Get application icon as web-compatible data URL
   */
  async getAppIconDataUrl(
    iconPath: string | null,
  ): Promise<Result<string | null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_app_icon_data_url", { iconPath }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Search for files using ripgrep command (Desktop only)
   */
  async searchFiles(
    options: SearchOptions,
    searchPath: string | null,
  ): Promise<Result<SearchResult[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("search_files", { options, searchPath }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Search for screenshot files (Desktop only)
   */
  async searchScreenshots(
    searchPath: string | null,
  ): Promise<Result<SearchResult[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("search_screenshots", { searchPath }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Get common search directories
   */
  async getSearchDirectories(): Promise<Result<string[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_search_directories"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Activate an MCP server
   */
  async activateMcpServer(
    name: string,
    config: JsonValue,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("activate_mcp_server", { name, config }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Deactivate an MCP server
   */
  async deactivateMcpServer(name: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("deactivate_mcp_server", { name }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Restart all MCP servers
   */
  async restartMcpServers(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("restart_mcp_servers") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Get list of connected MCP servers
   */
  async getConnectedServers(): Promise<Result<string[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_connected_servers"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Get available tools from MCP servers
   */
  async getTools(
    serverName: string | null,
  ): Promise<Result<ToolWithServer[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_tools", { serverName }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Call a tool on an MCP server
   */
  async callTool(
    toolName: string,
    arguments: { [key in string]: JsonValue } | null,
    cancellationToken: string | null,
  ): Promise<Result<CallToolResult, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("call_tool", {
          toolName,
          arguments,
          cancellationToken,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Cancel a running tool call
   */
  async cancelToolCall(
    cancellationToken: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("cancel_tool_call", { cancellationToken }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Get MCP configurations
   */
  async getMcpConfigs(): Promise<Result<string, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_mcp_configs") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Save MCP configurations
   */
  async saveMcpConfigs(configs: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("save_mcp_configs", { configs }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Get MCP server status
   */
  async getMcpServerStatus(): Promise<Result<McpServerStatus[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_mcp_server_status"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Reset MCP restart count for a specific server
   */
  async resetMcpRestartCount(
    serverName: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("reset_mcp_restart_count", { serverName }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

export const events = __makeEvents__<{
  demoEvent: DemoEvent;
}>({
  demoEvent: "demo-event",
});

/** user-defined constants **/

/** user-defined types **/

export type AppInfoWrapper = {
  name: string;
  bundle_id: string;
  path: string | null;
  icon: string | null;
};
export type CallToolResult = {
  content: JsonValue[];
  is_error: boolean;
  _meta: JsonValue | null;
};
export type DemoEvent = string;
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key in string]: JsonValue };
/**
 * MCP server status information
 */
export type McpServerStatus = {
  name: string;
  connected: boolean;
  active: boolean;
  restart_count: number;
};
export type SearchOptions = {
  pattern: string;
  max_results: number | null;
  file_extensions: string[] | null;
  include_hidden: boolean | null;
};
export type SearchResult = {
  path: string;
  line_number: number | null;
  content: string | null;
  file_type: string;
};
export type SystemInfo = { os: string; arch: string };
/**
 * Tool with server information
 */
export type ToolWithServer = {
  name: string;
  description: string | null;
  inputSchema: JsonValue;
  server: string;
};

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
