// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async greet(name: string): Promise {
    return await TAURI_INVOKE("greet", { name });
  },
  async executeCommand(command: string, args: string[]): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("execute_command", { command, args }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getSystemInfo(): Promise {
    return await TAURI_INVOKE("get_system_info");
  },
  async createPluginWindow(windowId: string, config: JsonValue): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("create_plugin_window", { windowId, config }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async updatePluginWindow(windowId: string, config: JsonValue): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("update_plugin_window", { windowId, config }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getApplications(): Promise {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_applications") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getFrontmostApp(): Promise {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_frontmost_app") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async refreshApplicationsList(): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("refresh_applications_list"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async refreshApplicationsListInBg(): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("refresh_applications_list_in_bg"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * Hide All Apps Except Frontmost (macOS only)
   */
  async hideAllAppsExceptFrontmost(): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("hide_all_apps_except_frontmost"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async closePluginWindow(windowId: string): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("close_plugin_window", { windowId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async focusPluginWindow(windowId: string): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("focus_plugin_window", { windowId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async setWindowFullscreen(windowId: string, fullscreen: boolean): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("set_window_fullscreen", {
          windowId,
          fullscreen,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async requestScreenshotPermission(): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("request_screenshot_permission"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async toggleWindowVisibility(): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("toggle_window_visibility"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async hideWindow(): Promise {
    try {
      return { status: "ok", data: await TAURI_INVOKE("hide_window") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async initializeAgent(config: AgentConfig, apiKey: string | null): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("initialize_agent", { config, apiKey }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async chatWithAgent(message: string): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("chat_with_agent", { message }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getConversationHistory(): Promise {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_conversation_history"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async clearConversation(): Promise {
    try {
      return { status: "ok", data: await TAURI_INVOKE("clear_conversation") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async isAgentInitialized(): Promise {
    try {
      return { status: "ok", data: await TAURI_INVOKE("is_agent_initialized") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getAgentConfig(): Promise {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_agent_config") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

export const events = __makeEvents__<{
  demoEvent: DemoEvent;
}>({
  demoEvent: "demo-event",
});

/** user-defined constants **/

/** user-defined types **/

export type AgentConfig = {
  model: string;
  preamble: string | null;
  temperature: number | null;
  max_tokens: number | null;
};
export type AgentResponse = {
  response: string;
  model_used: string;
  tokens_used: number | null;
};
export type AppInfoWrapper = {
  name: string;
  bundle_id: string;
  path: string | null;
  icon: string | null;
};
export type ChatMessage = { role: string; content: string; timestamp: string };
export type DemoEvent = string;
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key in string]: JsonValue };
export type SystemInfo = { os: string; arch: string };

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (cb: TAURI_API_EVENT.EventCallback) => ReturnType;
  once: (cb: TAURI_API_EVENT.EventCallback) => ReturnType;
  emit: null extends T
    ? (payload?: T) => ReturnType
    : (payload: T) => ReturnType;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record>(mappings: Record) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__ & {
        (handle: __WebviewWindow__): __EventObj__;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
